# Generated by Django 3.2.7 on 2021-09-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_newsimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('name',), 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterIndexTogether(
            name='news',
            index_together={('id', 'slug')},
        ),
    ]
