# Generated by Django 3.2.7 on 2021-09-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_brand_brandimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description3',
            field=models.TextField(blank=True),
        ),
    ]
