# Generated by Django 3.2.7 on 2021-09-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_brand_description3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='brand/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='discountimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='discount/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='movieimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='movie/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='topicsimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='topics/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
