# Generated by Django 3.2.7 on 2021-09-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_dog_dogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catimage',
            name='cat',
        ),
        migrations.AlterIndexTogether(
            name='dog',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='dogimage',
            name='dog',
        ),
        migrations.AlterIndexTogether(
            name='tovar',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='tovarimage',
            name='tovar',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='CatImage',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.DeleteModel(
            name='DogImage',
        ),
        migrations.DeleteModel(
            name='Tovar',
        ),
        migrations.DeleteModel(
            name='TovarImage',
        ),
    ]
